# Generated by Django 4.2.1 on 2023-05-10 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='Kit',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='Toner',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='Tray',
        ),
        migrations.DeleteModel(
            name='Kit',
        ),
        migrations.DeleteModel(
            name='Printer',
        ),
        migrations.DeleteModel(
            name='Toner',
        ),
        migrations.DeleteModel(
            name='Tray',
        ),
    ]
